services:
  celestia:
    build:
      context: .
      args:
        GO_VERSION: 1.22
        REPO: REPO_PLACEHOLDER
        PROJECT_FOLDER: celestia-app
        VERSION: VERSION_PLACEHOLDER
        DAEMON_NAME: celestia-appd
        CHAIN_ID: CHAIN_ID_PLACEHOLDER
        MONIKER: MONIKER_PLACEHOLDER
        GENESIS_FILE: GENESIS_FILE_PLACEHOLDER # TODO: example.rpc/genesis_chunked
        DAEMON_HOME: /root/.celestia-app
        ADDRBOOK: https://snapshots.polkachu.com/testnet-addrbook/cosmos/addrbook.json
        PEERS: PEERS_PLACEHOLDER
        SEEDS: SEEDS_PLACEHOLDER
        MIN_GAS_PRICES: MIN_GAS_PRICES_PLACEHOLDER
        DENOM: DENOM_PLACEHOLDER
        SNAPSHOT: https://testnet-files.itrocket.net/celestia/snap_celestia.tar.lz4
    container_name: klein-node
    restart: always
    ports:
      - 26657:26657
      - 26656:26656
      - 1317:1317
      - 9090:9090
    volumes:
      - klein-node-volume:/root/.celestia-app
volumes:
  klein-node-volume: