services:
  celestia:
    build:
      context: .
      args:
        GO_VERSION: 1.22
        REPO: REPO_PLACEHOLDER
        PROJECT_FOLDER: celestia-app
        VERSION: VERSION_PLACEHOLDER
        DAEMON_NAME: celestia-appd
        CHAIN_ID: CHAIN_ID_PLACEHOLDER
        MONIKER: MONIKER_PLACEHOLDER
        GENESIS_FILE: GENESIS_FILE_PLACEHOLDER
        DAEMON_HOME: /root/.celestia-app
        ADDRBOOK: https://snapshots.polkachu.com/testnet-addrbook/cosmos/addrbook.json
        PEERS: PEERS_PLACEHOLDER
        SEEDS: SEEDS_PLACEHOLDER
        MIN_GAS_PRICES: MIN_GAS_PRICES_PLACEHOLDER
        DENOM: DENOM_PLACEHOLDER
        RPC_URL: RPC_URL_PLACEHOLDER
    container_name: klein-node-celestia
    restart: always
    ports:
      - 26657:3000
    volumes:
      - celestia-volume:/root/.celestia-app
volumes:
  celestia-volume: